server:
  port: 8080
spring:
  application:
    name: "MyPost"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/myPostDb
    username: root
    password: admin
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: admin



management:
  endpoints:
    web:
      exposure:
        include: "*"


